// ids - THESE WILL BE PHASED OUT AS WE MOVE TO DYNAMICALLY GENERATED IDS
export const TRANSIT_WIDGET_ID = 'transit';
export const SLACK_WIDGET_ID = 'slack';
export const GITHUB_WIDGET_ID = 'github';
// types
export const TRANSIT_WIDGET = 'transit';
export const SLACK_WIDGET = 'slack';
export const GITHUB_WIDGET = 'github';
// reducers
export const ADD_WIDGET = 'ADD_WIDGET';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';
export const SHOW_ADD_WIDGET_MODAL = 'SHOW_ADD_WIDGET_MODAL';
export const HIDE_ADD_WIDGET_MODAL = 'HIDE_ADD_WIDGET_MODAL';
export const SHOW_DASHBOARD_SIDEBAR = 'SHOW_DASHBOARD_SIDEBAR';
export const HIDE_DASHBOARD_SIDEBAR = 'HIDE_DASHBOARD_SIDEBAR';
export const SHOW_WIDGET_SIDEBAR = 'SHOW_WIDGET_SIDEBAR';
export const HIDE_WIDGET_SIDEBAR = 'HIDE_WIDGET_SIDEBAR';
export const LOCK_DASHBOARD = 'LOCK_DASHBOARD';
export const UNLOCK_DASHBOARD = 'UNLOCK_DASHBOARD';
